### ISSUE TITLE
TypeError in line 609 of fontreport.py

### ISSUE THREAD

**Issue by mekkablue** [googlei18n/fontreport#5]
Trying it on a TTF, I got this Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/fontreport", line 9, in <module>
    load_entry_point('fontreport==1.0', 'console_scripts', 'fontreport')()
  File "build/bdist.macosx-10.10-x86_64/egg/fontreport/fontreport.py", line 609, in main
TypeError: must be unicode, not str
```

**Comment by anthrotype** [comment]
are you using python 3?
