### ISSUE TITLE
please add support for TTC (by allowing to select a font within TTC to report on)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontreport#7]
current behavior
$ fontreport SourceHanSerif2ND-Regular.ttc SourceHanSerif2ND-Regular.pdf

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/fontreport", line 9, in <module>
    load_entry_point('fontreport==1.0', 'console_scripts', 'fontreport')()
  File "build/bdist.macosx-10.6-intel/egg/fontreport/fontreport.py", line 597, in main
  File "build/bdist.macosx-10.6-intel/egg/fontreport/fontreport.py", line 69, in **init**
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/**init**.py", line 180, in **init**
    self.reader = sfnt.SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/Users/marekj/Library/Python/2.7/lib/python/site-packages/FontTools/fontTools/ttLib/sfnt.py", line 62, in **init**
    raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))

fontTools.ttLib.TTLibError: specify a font number between 0 and 2 (inclusive)

**Comment by marekjez86** [comment]
Note that I also filed https://github.com/googlei18n/fontdiff/issues/6 ; if there's something that needs to be done here please coordinate with the https://github.com/googlei18n/fontdiff component owner so the tools look like they have a common interface.

**Comment by KatMomoi** [comment]
Igor, can you update this bug?

**Comment by iverg** [comment]
Fixed
